In [27]:
import edgar
import pandas as pd
edgar.set_identity("sachiomaximilliano166@gmail.com")
nvda = edgar.Company("NVDA")
tenk = nvda.get_filings(form="10-Q")[50].obj()
tenk.cash_flow_statement.to_dataframe()

,concept,label,standard_concept,2009-07-26 (YTD),2008-07-27 (YTD),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_StatementOfCashFlowsAbstract,CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS,NaN,NaN,NaN,0,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,NaN
1,us-gaap_NetCashProvidedByUsedInOperatingActivi...,Cash flows from operating activities:,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
2,us-gaap_NetIncomeLoss,Net Income,NetIncome,-306640000.0,55876000.0,5,False,False,False,None,None,None,None,credit,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,us-gaap_NetCashProvidedByUsedInOperatingActivi...
3,nvda_AdjustmentsToReconcileNetIncomeLossToNetC...,Adjustments to reconcile net income (loss) to ...,NaN,NaN,NaN,4,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...
4,us-gaap_StockOptionPlanExpense,Net Cash from Operating Activities,NetCashFromOperatingActivities,135735000.0,0.0,5,False,False,False,None,None,None,None,NaN,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_AdjustmentsToReconcileNetIncomeLossToNetC...
5,us-gaap_DepreciationAndAmortization,Depreciation Expense,DepreciationExpense,99980000.0,87664000.0,5,False,False,False,None,None,None,None,debit,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_AdjustmentsToReconcileNetIncomeLossToNetC...
6,us-gaap_ShareBasedCompensation,Stock-Based Compensation Expense,StockBasedCompensationExpense,59489000.0,81423000.0,5,False,False,False,None,None,None,None,debit,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_AdjustmentsToReconcileNetIncomeLossToNetC...
7,us-gaap_AdjustmentsNoncashItemsToReconcileNetI...,Other,NaN,2453000.0,3145000.0,5,False,False,False,None,None,None,None,NaN,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_AdjustmentsToReconcileNetIncomeLossToNetC...
8,us-gaap_DeferredIncomeTaxExpenseBenefit,Income Tax Expense,IncomeTaxes,-28031000.0,5547000.0,5,False,False,False,None,None,None,None,debit,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_AdjustmentsToReconcileNetIncomeLossToNetC...
9,nvda_PaymentsUnderPatentLicensingArrangement,Payments under patent licensing arrangement,NaN,-616000.0,-26680000.0,5,False,False,False,None,None,None,None,NaN,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_AdjustmentsToReconcileNetIncomeLossToNetC...
10,nvda_ChangesInOperatingAssetsAndLiabilitiesNet...,"Changes in operating assets and liabilities, n...",NaN,NaN,NaN,4,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...
11,us-gaap_IncreaseDecreaseInAccountsReceivable,Accounts receivable,NaN,-33758000.0,-12373000.0,5,False,False,False,None,None,None,None,NaN,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_ChangesInOperatingAssetsAndLiabilitiesNet...
12,us-gaap_IncreaseDecreaseInInventories,Inventories,NaN,256564000.0,-73139000.0,5,False,False,False,None,None,None,None,NaN,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_ChangesInOperatingAssetsAndLiabilitiesNet...
13,nvda_PrepaidExpensesAndOtherCurrentAsset,Prepaid expenses and other current assets,NaN,-14325000.0,9136000.0,5,False,False,False,None,None,None,None,NaN,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_ChangesInOperatingAssetsAndLiabilitiesNet...
14,nvda_DepositsAndOtherAssetsOperating,Deposits and other assets,NaN,-2824000.0,-491000.0,5,False,False,False,None,None,None,None,NaN,1.0,1.0,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_ChangesInOperatingAssetsAndLiabilitiesNet...
15,us-gaap_IncreaseDecreaseInAccountsPayable,Accounts payable,NaN,56486000.0,-87730000.0,5,False,False,False,None,None,None,None,NaN,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_ChangesInOperatingAssetsAndLiabilitiesNet...
16,nvda_AccruedLiabilitiesAndOtherLongTermLiabili...,Accrued liabilities and other long-term liabil...,NaN,52732000.0,183824000.0,5,False,False,False,None,None,None,None,NaN,1.0,NaN,us-gaap_NetCashProvidedByUsedInOperatingActivi...,nvda_ChangesInOperatingAssetsAndLiabilitiesNet...
17,us-gaap_NetCashProvidedByUsedInOperatingActivi...,Net cash provided by operating activities,NetCashFromOperatingActivities,277245000.0,226202000.0,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_CashAndCashEquivalentsPeriodIncreaseDe...,us-gaap_NetCashProvidedByUsedInOperatingActivi...
18,us-gaap_NetCashProvidedByUsedInInvestingActivi...,Cash flows from investing activities:,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
19,us-gaap_PaymentsToAcquireMarketableSecurities,Purchases of marketable securities,InvestmentPurchases,530110000.0,678704000.0,5,False,False,False,None,None,None,None,credit,-1.0,1.0,us-gaap_NetCashProvidedByUsedInInvestingActivi...,us-gaap_NetCashProvidedByUsedInInvestingActivi...
20,us-gaap_ProceedsFromSaleAndMaturityOfMarketabl...,Proceeds from Investments,InvestmentProceeds,427699000.0,810508000.0,5,False,False,False,None,None,None,None,NaN,1.0,NaN,us-gaap_NetCashProvidedByUsedInInvestingActivi...,us-gaap_NetCashProvidedByUsedInInvestingActivi...
21,nvda_PurchasesOfPropertyAndEquipmentAndIntangi...,Purchases of property and equipment and intang...,NaN,-38433000.0,-255687000.0,5,False,False,False,None,None,None,None,debit,1.0,NaN,us-gaap_NetCashProvidedByUsedInInvestingActivi...,us-gaap_NetCashProvidedByUsedInInvestingActivi...
22,us-gaap_PaymentsToAcquireBusinessesNetOfCashAc...,"Acquisition of businesses, net of cash and cas...",AcquisitionsNet,0.0,27948000.0,5,False,False,False,None,None,None,None,credit,-1.0,1.0,us-gaap_NetCashProvidedByUsedInInvestingActivi...,us-gaap_NetCashProvidedByUsedInInvestingActivi...
23,us-gaap_PaymentsForProceedsFromOtherInvestingA...,Other,NetCashFromInvestingActivities,-782000.0,-1718000.0,5,False,False,False,None,None,None,None,NaN,-1.0,1.0,us-gaap_NetCashProvidedByUsedInInvestingActivi...,us-gaap_NetCashProvidedByUsedInInvestingActivi...
24,us-gaap_NetCashProvidedByUsedInInvestingActivi...,Net cash used in investing activities,NetCashFromInvestingActivities,-140062000.0,-150113000.0,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_CashAndCashEquivalentsPeriodIncreaseDe...,us-gaap_NetCashProvidedByUsedInInvestingActivi...
25,us-gaap_NetCashProvidedByUsedInFinancingActivi...,Cash flows from financing activities:,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
26,nvda_PaymentsRelatedToStockOptionPurchase,Payments related to stock option purchase,NaN,-78075000.0,0.0,5,False,False,False,None,None,None,None,debit,1.0,NaN,us-gaap_NetCashProvidedByUsedInFinancingActivi...,us-gaap_NetCashProvidedByUsedInFinancingActivi...
27,us-gaap_ProceedsFromIssuanceOfCommonStock,Stock Repurchases (Issuances),EquityExpenseIncome(BuybackIssued),47092000.0,39981000.0,5,False,False,False,None,None,None,None,debit,1.0,NaN,us-gaap_NetCashProvidedByUsedInFinancingActivi...,us-gaap_NetCashProvidedByUsedInFinancingActivi...
28,us-gaap_PaymentsForRepurchaseOfCommonStock,Payments related to repurchases of common stock,EquityExpenseIncome(BuybackIssued),0.0,123896000.0,5,False,False,False,None,None,None,None,credit,-1.0,1.0,us-gaap_NetCashProvidedByUsedInFinancingActivi...,us-gaap_NetCashProvidedByUsedInFinancingActivi...
29,us-gaap_RepaymentsOfLongTermCapitalLeaseObliga...,Payments under capital lease obligations,CapitalLeasePaymentsCF,103000.0,0.0,5,False,False,False,None,None,None,None,NaN,-1.0,1.0,us-gaap_NetCashProvidedByUsedInFinancingActivi...,us-gaap_NetCashProvidedByUsedInFinancingActivi...
30,us-gaap_NetCashProvidedByUsedInFinancingActivi...,Net cash used in financing activities,NetCashFromFinancingActivities,-31086000.0,-83915000.0,4,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_CashAndCashEquivalentsPeriodIncreaseDe...,us-gaap_NetCashProvidedByUsedInFinancingActivi...
31,us-gaap_CashAndCashEquivalentsPeriodIncreaseDe...,Change in cash and cash equivalents,NaN,106097000.0,-7826000.0,3,False,False,False,None,None,None,None,NaN,1.0,1.0,NaN,us-gaap_StatementLineItems
32,us-gaap_CashAndCashEquivalentsAtCarryingValue,Cash and cash equivalents at end of period,CashAndMarketableSecurities,523785000.0,719143000.0,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_StatementLineItems
33,us-gaap_CashAndCashEquivalentsAtCarryingValue,Cash and cash equivalents at end of period,CashAndMarketableSecurities,523785000.0,719143000.0,3,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_AssetsCurrent,us-gaap_StatementLineItems
34,nvda_SupplementalDisclosuresOfCashFlowInformation,Supplemental disclosures of cash flow informat...,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
35,us-gaap_IncomeTaxesPaidNet,Income Tax Expense,IncomeTaxes,1693000.0,4459000.0,4,False,False,False,None,None,None,None,NaN,NaN,NaN,NaN,nvda_SupplementalDisclosuresOfCashFlowInformation
36,nvda_CashPaidForInterestOnCapitalLeaseObligations,Cash paid for interest on capital lease oblig...,NaN,1643000.0,0.0,4,False,False,False,None,None,None,None,NaN,NaN,NaN,NaN,nvda_SupplementalDisclosuresOfCashFlowInformation
37,nvda_OtherNonCashActivities,Other non-cash activities:,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
38,us-gaap_LiabilitiesAssumed,Assets acquired by assuming related liabilities,NaN,6288000.0,68408000.0,4,False,False,False,None,None,None,None,NaN,NaN,NaN,NaN,nvda_OtherNonCashActivities
39,us-gaap_UnrealizedGainLossOnSecurities,Non-Operating Income (Expense),NonoperatingIncomeExpense,4805000.0,-11252000.0,4,False,False,False,None,None,None,None,NaN,NaN,NaN,NaN,nvda_OtherNonCashActivities

In [6]:
print(tenk.income_statement)

                                        NVIDIA CORP   NVDA
                                        CONSOLIDATED STATEMENT OF INCOME
                                        Jan 28, 2024 to Jan 25, 2026

                                                                  Jan 25, 2026   Jan 26, 2025   Jan 28, 2024
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────
        Revenue:                                                      $215,938       $130,497        $60,922
        Data Center                                                   $193,737       $115,186        $47,525
          Compute                                                     $162,361       $102,196        $38,950
          Networking                                                   $31,376        $12,990         $8,575
        Gaming                                                         $16,042        $11,350        $10,447
        Professional Visualization                                      $3,191         $1,878         $1,553
        Automotive                                                      $2,349         $1,694         $1,091
        OEM and Other                                                     $619           $389           $306
        Cost of revenue:                                               $62,475        $32,639        $16,621
        Inventory purchase obligations in excess of projections         $3,200         $2,000
      Gross profit                                                    $153,463        $97,858        $44,301
    Operating expenses
          Research and development                                     $18,497        $12,914         $8,675
          Sales, general and administrative                             $4,579         $3,491         $2,654
          Total operating expenses                                     $23,076        $16,405        $11,329
      Operating income:                                               $130,387        $81,453        $32,972
        Interest income:                                                $2,300         $1,786           $866
        Interest expense:                                               $(259)         $(247)         $(257)
        Other income, net:                                              $9,022         $1,034           $237
      Total other income, net                                          $11,063         $2,573           $846
      Income before income tax:                                       $141,450        $84,026        $33,818
      Income tax expense                                               $21,383        $11,146         $4,058
      Net income:                                                     $120,067        $72,880        $29,760
    Net income per share:
        Basic (in USD per share)                                          4.93           2.97           1.21
        Diluted (in USD per share)                                        4.90           2.94           1.19
    Weighted average shares used in per share computation:
        Basic (in shares)                                               24,359         24,555         24,690
        Diluted (in shares)                                             24,514         24,804         24,940

   Source: SEC XBRL  •  (In millions, except shares and per share data)

In [8]:
print(tenk.risk_factors)

Item 1A. Risk Factors

The following risk factors should be considered in addition to the other information in this Annual Report on Form 10-K. The following risks could harm our business, financial condition, results of operations or reputation, which could cause our stock price to decline. Additional risks, trends and uncertainties not presently known to us or that we currently believe are immaterial may also harm our business, financial condition, results of operations or reputation.

Risk Factors Summary

Risks Related to Our Industry and Markets

•Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.

•Competition could adversely impact our market share and financial results.

Risks Related to Demand, Supply, and Manufacturing

•Long manufacturing lead times and uncertain supply and capacity availability, combined with a failure to estimate customer demand accurately has led and could lead to mismatches between supply and demand.

•Dependency on third-party suppliers and their technology to manufacture, assemble, test, or package our products reduces our control over product quantity and quality, manufacturing yields, and product delivery schedules and could harm our business.

•Defects in our products have caused and could cause us to incur significant expenses to remediate and could damage our business.

Risks Related to Our Global Operating Business

•Adverse economic conditions may harm our business.

•International sales and operations are a significant part of our business, which exposes us to risks that could harm our business.

•Product, system security and data protection incidents or breaches, as well as cyber-attacks could disrupt our operations and adversely affect our financial condition, stock price and reputation.

•Business disruptions could harm our operations and financial results.

•Climate change may have a long-term impact on our business.

•We may not be able to realize the potential benefits of business investments or acquisitions, nor successfully integrate acquisition targets.

•A significant amount of our revenue stems from a limited number of partners and distributors and we have a concentration of sales to customers who purchase directly or indirectly from us, and our revenue could be adversely affected if we lose or are prevented from selling to any of these customers.

•Commercial arrangements expose us to counterparty risks, which may negatively impact our business, financial condition, or results of operations.

•We may be unable to attract, retain, and motivate our executives and key employees.

•Modification or interruption of our business processes and information systems may disrupt our business and internal controls.

•Our operating results have in the past fluctuated and may in the future fluctuate, and if our operating results are below the expectations of securities analysts or investors, our stock price could decline.

Risks Related to Regulatory, Legal, Our Stock, and Other Matters

•We are subject to complex laws, rules, regulations, and political and other actions, including restrictions on the export of our products, which may adversely impact our business.

•Scrutiny regarding our corporate sustainability practices could result in financial, reputational, or operational harm and liability.

•Issues relating to the responsible use of our technologies, including AI, may result in reputational or financial harm and liability.

•Adequately protecting our IP rights could be costly, and our ability to compete could be harmed if we are unsuccessful or if we are prohibited from making or selling our products.

•We are subject to stringent and changing data privacy and security laws, rules, regulations, and other obligations. These areas could damage our reputation, deter customers, affect product design, or result in legal or regulatory proceedings and liability.

•Our operating results may be adversely impacted by additional tax liabilities, higher than expected tax rates, changes in tax laws, and other tax-related factors.

•Our business is exposed to the burden and risks associated with litigation, investigations, and regulatory proceedings.

•Delaware law, provisions in our governing documents and our agreement with Microsoft could delay or prevent a change in control.

Risk Factors

Risks Related to Our Industry and Markets

Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.

Our accelerated computing platforms experience rapid changes in technology, customer requirements, competitive products, and industry standards.

Our success depends on our ability to:

•timely identify industry changes, adapt our strategies, and develop new or enhance and maintain existing products and technologies that meet the evolving needs of our markets, including addressing unexpected shifts in industry standards or disruptive technological innovations that could render our products incompatible with those developed by other companies;

•develop or secure access to new products and technologies through investments in research and development;

•launch new offerings with new business models including software, services, and cloud solutions, as well as software-, infrastructure-, or platform-as-a-service solutions;

•expand the ecosystem for our products and technologies;

•meet evolving and prevailing customer and industry safety, security, reliability expectations, and compliance standards;

•manage product and software lifecycles to maintain customer and end-user satisfaction;

•develop, acquire, maintain, and secure access to the internal and external infrastructure needed to scale our business, including sufficient energy for powering data centers using our products, acquisition integrations, customer support, e-commerce, IP licensing capabilities, and cloud service capacity; and

•complete technical, financial, operational, compliance, sales and marketing investments for the above activities.

We have invested in research and development in markets where we have a limited operating history, which may not produce meaningful revenue for several years, if at all. If we fail to develop or monetize new products and technologies, or if they do not become widely adopted, our financial results could be adversely affected. Obtaining design wins may involve a lengthy process and depends on our ability to anticipate and provide features and functionality that customers will demand. They also do not guarantee revenue. Failure to obtain a design win may prevent us from obtaining future design wins in subsequent generations. We cannot ensure that our products and technologies will provide value to our customers and partners. If we fail any of these key success criteria, our financial results may be harmed.

We have entered into an intellectual property license arrangement with Groq, Inc., or Groq, that required significant, nonrefundable payments. Successfully incorporating the licensed technology into our architectures and product roadmaps requires significant engineering effort and may not occur on expected timelines or at all. The licensed technology may not achieve the desired results as designed or achieve customer or ecosystem adoption. The economic outcomes of this arrangement depend on our ability to translate the licensed technology into commercially viable products and services over time, and we may be unable to recover the associated costs or realize an adequate return on this spend. If our efforts to use the licensed technology are delayed or unsuccessful, our business, operating results, and financial condition could be negatively impacted.

We entered into multi-year cloud service agreements to support our research and development activities. The timing and availability of these cloud services have changed and may continue to shift, impacting our revenue, expenses, and development timelines, and these arrangements may not deliver anticipated benefits. We also offer or plan to offer standalone software solutions, including NVIDIA AI Enterprise, NVIDIA Omniverse, NVIDIA DRIVE, and other software products. These business models or strategies may not be successful, and we may fail to sell any meaningful standalone software or services. We may incur significant costs and may not achieve any significant revenue from these offerings.

Competition could adversely impact our market share and financial results.

Our target markets remain competitive, and competition may intensify with expanding and changing product and service offerings, industry standards, customer and market needs, new entrants and consolidations. Our competitors’ products, services and technologies, including those mentioned above in this Annual Report on Form 10-K, may be cheaper or provide better functionality or features than ours, which has resulted and may in the future result in lower-than-expected selling prices or demand for our products. Some of our competitors operate their own fabrication facilities, and have longer operating histories, larger customer bases, more comprehensive IP portfolios and patent protections, more design wins, and greater financial, sales, marketing and distribution resources than we do. These competitors may be able to acquire market share and/or prevent us from doing so, more effectively identify and capitalize upon opportunities in new markets and end-user trends, more quickly transition their products, and impinge on our ability to procure sufficient

14


foundry capacity and scarce input materials during a supply-constrained environment, which could harm our business. Some of our customers have in-house expertise and internal development capabilities similar to some of ours and can use or develop their own solutions to replace those we are providing. For example, others may offer cloud-based services that compete with our AI cloud service offerings, and we may not be able to establish market share sufficient to achieve the scale necessary to meet our business objectives. If we are unable to successfully compete in this environment, demand for our products, services and technologies could decrease, which may negatively impact our business.

Risks Related to Demand, Supply, and Manufacturing

Long manufacturing lead times and uncertain supply and capacity availability, combined with a failure to estimate customer demand accurately, has led and could lead to mismatches between supply and demand.

We have long manufacturing lead times and build finished products and maintain inventory in advance of anticipated demand. In periods of shortages impacting the semiconductor industry and/or limited supply or capacity in our supply chain, the lead times for certain supply may be extended. We have previously experienced and may continue to experience extended lead times of more than 12 months. To secure future supply and capacity, we have paid premiums, provided deposits, and entered into long-term supply agreements and capacity commitments, which have increased our product costs and this may continue. We may still be unable to secure sufficient commitments for capacity to address our business needs.

If we inaccurately estimate demand, or our customers change orders, as we have experienced in the past, we may not be able to reduce our supply commitments in time, at the same rate, or at all. Significant mismatches between supply and demand have varied across our market platforms, resulted in both product shortages and excess inventory, significantly harmed our financial results and could reoccur. If we underestimate demand, and our foundry partners and contract manufacturers are unable to increase production or provide sufficient supply, we may not be able to meet increased customer demand in a timely manner, or at all. Our reputation and customer relationships could be damaged and we could lose revenue and market share. Additionally, since some of our products are part of a complex data center buildout, supply constraints or availability issues with respect to any one component have had and may have a broader revenue impact. For example, our ability to sell certain products has been and could be impeded if components necessary for the finished products are not available from third parties.

If we overestimate demand, or if customers cancel or defer orders or choose to purchase from our competitors, we may not be able to utilize on-hand inventory or reduce purchase commitments accordingly. We have had to reduce average selling prices, including due to our channel pricing programs, increase prices for certain of our products as a result of our suppliers’ increase in prices, write down our inventory, incur cancellation penalties, and record impairments, and may have to do so in the future. The impact of these risks would be amplified by our non-cancellable and non-returnable purchase orders placed in advance of our historical lead times and could be exacerbated if we need to make changes to the design of future products. These risks have increased and may continue to increase as our purchase obligations and prepaids have grown and are expected to continue to grow and become a greater portion of our total supply. All of these factors may negatively impact our gross margins and financial results.

Factors that have caused and/or could in the future cause us to underestimate or overestimate demand, and impact the timing and volume of our revenue, include:

•changes in product development cycles and time to market;

•competing technologies and competitor product releases, announcements or other actions;

•changes in business and economic conditions;

•sudden or sustained government lockdowns or public health issues;

•rapidly changing technology or customer requirements;

•the availability of sufficient data center capacity or energy for customers to procure;

•new product introductions and transitions resulting in less demand for existing products;

•new or unexpected end-use cases;

•increase in demand for competitive products;

•changes in end-user demand;

•purchasing decisions made, and inventory levels held by, distributors, ODMs, OEMs, system integrators, other channel partners and other third parties;

15


•the ability of developers, end customers and other third parties to build, enhance, and maintain accelerated computing applications that leverage our platforms;

•the demand for accelerated computing, AI-related cloud services, or large language models;

•changes that impact the ecosystem for the architectures underlying our products and technologies;

•government actions or changes in governmental policies, such as export controls, increased restrictions on gaming usage, or tariffs;

•our customers’ and partners’ ability to secure capital and energy and to build complex datacenter infrastructure timely; and

•the availability of third-party content on our platforms, such as GeForce NOW.

The availability of data centers, energy, and capital to support the buildout of NVIDIA AI infrastructure by our customers and partners is crucial, and any shortage of these and other necessary resources could impact our future revenue and financial performance. Expanding energy capacity to meet demand is a complex, multi-year process involving significant regulatory, technical, and construction challenges. In addition, access to capital can be particularly constrained for less-capitalized companies, which may face difficulties securing financing for large-scale infrastructure projects. These limitations could delay customer and partner deployments or reduce the scale of accelerated computing and AI adoption.

Challenges in estimating demand could become more pronounced or volatile in the future on both a global and regional basis. Extended lead times may occur if we experience other supply constraints caused by natural disasters, pandemics or other events. Geopolitical tensions in regions where we rely on suppliers, contract manufacturers, and assembly partners that are critical to our supply continuity, could have a material adverse impact on us. Publicly announced intentions by governments or other companies to purchase our products can further complicate our demand estimates, as such announcements are often non-binding and may not result in committed volumes.

We continue to increase our supply and capacity purchases with existing and new suppliers to support our demand projections and increasing complexity of our data center products. We expect supply constraints to be a headwind to Gaming in the first quarter of fiscal year 2027 and beyond. We have also entered and may continue to enter into prepaid manufacturing and capacity agreements to supply both current and future products. The increased purchase volumes and integration of new suppliers and contract manufacturers into our supply chain creates more complexity in managing multiple suppliers with variations in production planning, execution and logistics. Our expanding product portfolio and varying component compatibility and quality may lead to increased inventory levels. We have incurred and may in the future incur inventory provisions or impairments if our inventory or supply or capacity commitments exceed demand for our products or demand declines.

We are increasing our U.S.-based manufacturing and investing in specialized equipment and processes to support domestic production. We may experience delays or difficulties in scaling production as planned. Our ability to increase manufacturing capabilities will depend on the domestic manufacturing ecosystem's capacity to ramp production supply to the required volume timely. Delays or shortfalls could impact our ability to meet demand.

Product transitions are complex and we often ship both new and prior architecture products simultaneously as our channel partners prepare to ship and support new products. We are generally in various stages of transitioning the architectures of our Data Center, Gaming, Professional Visualization, and Automotive products. The computing industry is experiencing a broader and faster launch cadence of accelerated computing platforms to meet a growing and diverse set of AI opportunities. We have introduced a new product and architecture cadence of our Data Center solutions where we seek to complete new computing solutions each year and provide a greater variety of Data Center offerings. The increased frequency of these transitions and the larger number of products and product configurations may magnify the challenges associated with managing our supply and demand which may further create volatility in our revenue. Qualification time for new products, customers anticipating product transitions, and channel partners reducing channel inventory of prior architectures ahead of new product introductions can reduce, or create volatility in, our revenue. Customers may delay adopting new architectures if their data center infrastructure is not ready, which could affect the timing of our revenue. We have experienced and may in the future experience reduced demand for current generation architectures when customers anticipate transitions, and we may be unable to sell multiple product architectures at the same time for current and future architecture transitions. Our financial results have been and may in the future be negatively impacted if we are unable to execute our architectural transitions as planned for any reason. The increased frequency and complexity of newly introduced products could result in unanticipated quality or production issues that could increase the magnitude of inventory provisions, warranty, or other costs or result in product delays. For example, our gross margins in the second quarter of fiscal year 2025 were negatively impacted by inventory provisions for low-yielding Blackwell material.


In [13]:
facts = edgar.Company("GOOG").get_facts()

# Common metrics
print(facts.get_revenue())
print(facts.get_net_income())
print(facts.get_total_assets())
# Any XBRL concept
print(facts.get_concept("AccountsPayableCurrent"))

# Time series
revenue_ts = facts.time_series("Revenues")
print(revenue_ts)    # every quarter going back years

350018000000.0
132170000000.0
595281000000.0
None
   period_start  period_end  duration_days  numeric_value fiscal_period  \
0    2025-01-01  2025-03-31             89   9.023400e+10            Q1
1    2026-01-01  2026-03-31             89   1.098960e+11            Q1
2    2023-01-01  2023-12-31            364   3.073940e+11            FY
3    2024-01-01  2024-12-31            365   3.500180e+11            FY
4    2025-01-01  2025-12-31            364   4.028360e+11            FY
5    2024-01-01  2024-09-30            273   2.535490e+11            Q3
6    2024-07-01  2024-09-30             91   8.826800e+10            Q3
7    2025-01-01  2025-09-30            272   2.890070e+11            Q3
8    2025-07-01  2025-09-30             91   1.023460e+11            Q3
9    2024-01-01  2024-06-30            181   1.652810e+11            Q2
10   2024-04-01  2024-06-30             90   8.474200e+10            Q2
11   2025-01-01  2025-06-30            180   1.866620e+11            Q2
12   2025-04-01  2025-06-30             90   9.642800e+10            Q2
13   2019-01-01  2019-12-31            364   1.618570e+11            FY
14   2020-01-01  2020-12-31            365   1.825270e+11            FY
15   2021-01-01  2021-12-31            364   2.576370e+11            FY
16   2020-01-01  2020-06-30            181   7.945600e+10            Q2
17   2020-04-01  2020-06-30             90   3.829700e+10            Q2
18   2021-01-01  2021-06-30            180   1.171940e+11            Q2
19   2021-04-01  2021-06-30             90   6.188000e+10            Q2

    fiscal_year
0          2026
1          2026
2          2025
3          2025
4          2025
5          2025
6          2025
7          2025
8          2025
9          2025
10         2025
11         2025
12         2025
13         2021
14         2021
15         2021
16         2021
17         2021
18         2021
19         2021

C:\Users\Sachio\AppData\Local\Temp\ipykernel_40192\3854283658.py:8: UserWarning: Unknown concept 'AccountsPayableCurrent'.
  Use list_supported_concepts() to see available concept names,
  or search_concepts() to search this company's raw XBRL tags.
  print(facts.get_concept("AccountsPayableCurrent"))

,label,depth,is_abstract,is_total,section,confidence,Q1 2026,Q4 2025,Q3 2025,Q2 2025,...,Q3 2023,Q2 2023,Q1 2023,Q4 2022,Q3 2022,Q2 2022,Q1 2022,Q4 2021,Q3 2021,Q2 2021
concept,,,,,,,,,,,,,,,,,,,,,
NetCashProvidedByUsedInOperatingActivitiesAbstract,Cash flows from operating activities:,0,True,False,NaN,0.791541,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ProfitLoss,"Net Income (Loss), Including Portion Attributa...",1,False,True,NaN,0.540785,7.349000e+09,8.518000e+09,4.140000e+09,4.965000e+09,...,3.303000e+09,3.481000e+09,3.774000e+09,3.359000e+09,3.074000e+09,2.590000e+09,2.472000e+09,1.989000e+09,1.876000e+09,1.493000e+09
AdjustmentsToReconcileNetIncomeLossToCashProvidedByUsedInOperatingActivitiesAbstract,Adjustments to reconcile net income to net cas...,1,True,False,NaN,0.779456,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ShareBasedCompensation,"Share-based Payment Arrangement, Noncash Expense",2,False,False,NaN,0.667674,2.176000e+09,2.195000e+09,2.322000e+09,1.771000e+09,...,6.290000e+08,5.130000e+08,3.910000e+08,3.870000e+08,3.730000e+08,3.860000e+08,3.870000e+08,4.140000e+08,4.210000e+08,4.250000e+08
IncreaseDecreaseInOperatingCapitalAbstract,Changes in operating assets and liabilities:,2,True,False,NaN,0.712991,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IncreaseDecreaseInAccountsReceivable,Increase (Decrease) in Accounts Receivable,3,False,False,NaN,0.410876,1.315000e+09,6.510000e+08,9.370000e+08,5.900000e+08,...,-4.400000e+07,9.100000e+07,2.760000e+08,2.410000e+08,6.290000e+08,5.360000e+08,4.680000e+08,NaN,-5.000000e+07,1.410000e+08
IncreaseDecreaseInInventories,Increase (Decrease) in Inventories,3,False,False,NaN,0.374622,6.920000e+08,9.000000e+07,1.630000e+08,1.090000e+08,...,-4.400000e+07,-1.300000e+07,-2.600000e+07,8.700000e+07,1.700000e+08,1.470000e+08,2.230000e+08,1.370000e+08,1.560000e+08,5.200000e+07
IncreaseDecreaseInAccountsPayable,Increase (Decrease) in Accounts Payable,3,False,False,NaN,0.311178,5.340000e+08,1.180000e+08,1.360000e+08,-6.130000e+08,...,1.880000e+08,-1.140000e+08,-8.000000e+07,3.040000e+08,-3.520000e+08,-3.100000e+07,0.000000e+00,1.010000e+08,1.560000e+08,-5.800000e+07
Depreciation,Depreciation,2,False,False,NaN,0.263200,1.500000e+08,1.480000e+08,1.420000e+08,1.420000e+08,...,1.220000e+08,1.290000e+08,1.270000e+08,1.290000e+08,1.290000e+08,1.350000e+08,1.360000e+08,1.340000e+08,1.340000e+08,1.330000e+08
NetCashProvidedByUsedInOperatingActivities,Net Cash Provided by (Used in) Operating Activ...,1,False,True,NaN,0.885196,8.260000e+09,7.703000e+09,7.166000e+09,6.555000e+09,...,4.719000e+09,4.502000e+09,4.036000e+09,4.583000e+09,4.424000e+09,4.243000e+09,3.486000e+09,3.541000e+09,3.541000e+09,3.569000e+09
NetCashProvidedByUsedInInvestingActivitiesAbstract,Cash flows from investing activities:,0,True,False,NaN,0.752266,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentsToAcquireBusinessesNetOfCashAcquired,"Payments to Acquire Businesses, Net of Cash Ac...",1,False,False,NaN,0.377644,NaN,0.000000e+00,0.000000e+00,0.000000e+00,...,1.700000e+07,0.000000e+00,NaN,7.000000e+06,5.000000e+06,2.260000e+08,NaN,0.000000e+00,0.000000e+00,0.000000e+00
NetCashProvidedByUsedInInvestingActivities,Net Cash Provided by (Used in) Investing Activ...,1,False,True,NaN,0.851964,-1.150000e+08,NaN,9.400000e+07,-3.070000e+08,...,-5.650000e+08,-4.210000e+08,-1.030000e+08,NaN,8.000000e+07,-6.190000e+08,-3.090000e+08,5.000000e+07,-2.950000e+08,-2.480000e+08
PaymentsForProceedsFromOtherInvestingActivities,Payments for (Proceeds from) Other Investing A...,1,False,False,NaN,0.377644,-5.000000e+06,-1.050000e+08,1.600000e+07,1.000000e+07,...,-1.200000e+07,-1.000000e+06,0.000000e+00,-1.000000e+06,-1.000000e+06,-9.000000e+06,8.000000e+06,9.000000e+06,0.000000e+00,3.000000e+06
PaymentsToAcquirePropertyPlantAndEquipment,"Payments to Acquire Property, Plant, and Equip...",1,False,False,NaN,0.513595,2.500000e+08,2.370000e+08,1.420000e+08,1.440000e+08,...,1.220000e+08,1.220000e+08,1.030000e+08,1.220000e+08,1.160000e+08,8.500000e+07,1.010000e+08,8.800000e+07,1.150000e+08,1.260000e+08
NetCashProvidedByUsedInFinancingActivitiesAbstract,Cash flows from financing activities:,0,True,False,NaN,0.785498,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentsRelatedToTaxWithholdingForShareBasedCompensation,"Payment, Tax Withholding, Share-based Payment ...",1,False,False,NaN,0.323263,0.000000e+00,0.000000e+00,5.800000e+07,1.766000e+09,...,4.600000e+08,6.140000e+08,3.330000e+08,2.740000e+08,2.920000e+08,5.140000e+08,3.750000e+08,2.660000e+08,3.470000e+08,4.610000e+08
PaymentsForRepurchaseOfCommonStock,Payments for Repurchase of Common Stock,1,False,False,NaN,0.586103,7.850000e+09,0.000000e+00,0.000000e+00,2.450000e+09,...,1.707000e+09,2.806000e+09,1.188000e+09,0.000000e+00,1.500000e+09,2.776000e+09,2.724000e+09,0.000000e+00,NaN,NaN
NetCashProvidedByUsedInFinancingActivities,Net Cash Provided by (Used in) Financing Activ...,1,False,True,NaN,0.894260,-1.014900e+10,NaN,-1.825100e+10,-1.223700e+10,...,-1.305300e+10,-8.980000e+09,-3.702000e+09,NaN,-1.380000e+10,-1.026800e+10,-5.121000e+09,NaN,-6.441000e+09,-4.534000e+09
PaymentsOfDividendsCommonStock,"Payments of Ordinary Dividends, Common Stock",1,False,False,NaN,0.374622,3.086000e+09,2.797000e+09,2.786000e+09,2.785000e+09,...,1.901000e+09,1.914000e+09,1.926000e+09,1.707000e+09,1.661000e+09,1.676000e+09,1.689000e+09,1.486000e+09,1.482000e+09,1.477000e+09
ProceedsFromPaymentsForOtherFinancingActivities,Proceeds from (Payments for) Other Financing A...,1,False,False,NaN,0.350453,-3.700000e+07,-2.700000e+07,-7.000000e+06,-4.000000e+06,...,-5.000000e+06,-7.000000e+06,5.000000e+06,-5.000000e+06,-4.000000e+06,-4.000000e+06,-4.000000e+06,-1.000000e+06,-1.100000e+07,-2.000000e+06
ProceedsFromIssuanceOfCommonStock,Proceeds from Issuance of Common Stock,1,False,False,NaN,0.263200,NaN,1.030000e+08,0.000000e+00,1.170000e+08,...,0.000000e+00,6.200000e+07,NaN,5.400000e+07,0.000000e+00,5.900000e+07,1.000000e+06,5.700000e+07,7.000000e+06,7.100000e+07
CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect,"Cash, Cash Equivalents, Restricted Cash and Re...",0,False,True,NaN,0.797583,-2.004000e+09,5.460000e+09,1.246000e+09,1.650000e+08,...,5.020000e+08,-8.630000e+08,2.310000e+08,2.439000e+09,9.720000e+08,-3.158000e+09,-1.944000e+09,1.058000e+09,1.587000e+09,1.900000e+09
CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents,"Cash, Cash Equivalents, Restricted Cash and Re...",0,False,False,NaN,0.788520,1.417400e+10,NaN,1.071800e+10,9.472000e+09,...,1.205500e+10,1.155300e+10,1.264700e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SupplementalCashFlowInformationAbstract,Supplemental disclosure of cash flow information:,0,True,False,NaN,0.561934,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InterestPaidNet,"Interest Paid, Excluding Capitalized Interest,...",1,False,False,NaN,0.583082,6.190000e+08,6.990000e+08,6.020000e+08,7.000000e+08,...,3.480000e+08,3.970000e+08,3.610000e+08,3.970000e+08,2.900000e+08,4.590000e+08,2.400000e+08,5.710000e+08,2.530000e+08,3.690000e+08
IncomeTaxesPaidNet,"Income Taxes Paid, Net",1,False,False,NaN,0.374622,7.820000e+08,7.550000e+08,8.220000e+08,6.080000e+08,...,4.270000e+08,8.910000e+08,2.730000e+08,2.510000e+08,2.310000e+08,2.400000e+08,1.860000e+08,1.680000e+08,1.670000e+08,2.930000e+08
CashFlowNoncashInvestingAndFinancingActivitiesDisclosureAbstract,Non-cash transactions:,0,True,False,NaN,0.342100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CapitalExpendituresIncurredButNotYetPaid,"Property, plant and equipment acquisitions fun...",1,False,False,NaN,0.342100,2.500000e+08,2.370000e+08,3.860000e+08,2.440000e+08,...,3.470000e+08,2.250000e+08,1.030000e+08,1.220000e+08,3.020000e+08,1.860000e+08,1.010000e+08,8.800000e+07,3.550000e+08,2.400000e+08
AdditionalItems,Additional Financial Items,0,True,False,Additional,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AllocatedShareBasedCompensationExpense,"Share-based Payment Arrangement, Expense",1,False,False,Additional,0.500000,2.176000e+09,2.195000e+09,2.322000e+09,1.771000e+09,...,6.290000e+08,5.130000e+08,3.910000e+08,3.870000e+08,3.730000e+08,3.860000e+08,3.870000e+08,4.140000e+08,4.210000e+08,4.250000e+08
AmortizationOfFinancingCostsAndDiscounts,Amortization of Debt Issuance Costs and Discounts,1,False,False,Additional,0.500000,7.200000e+07,7.100000e+07,8.200000e+07,9.400000e+07,...,3.300000e+07,3.300000e+07,3.200000e+07,3.200000e+07,3.200000e+07,3.300000e+07,3.200000e+07,2.900000e+07,2.400000e+07,2.100000e+07
AmortizationOfIntangibleAssets,Amortization of Intangible Assets,1,False,False,Additional,0.500000,1.969000e+09,4.132000e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DiscontinuedOperationIncomeLossFromDiscontinuedOperationDuringPhaseOutPeriodNetOfTax,"Discontinued Operation, Income (Loss) from Dis...",1,False,True,Additional,0.500000,NaN,1.190000e+08,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DividendsPaid,Payments of Dividends,1,False,False,Additional,0.500000,3.086000e+09,2.797000e+09,8.345000e+09,5.559000e+09,...,5.741000e+09,3.840000e+09,1.926000e+09,1.782000e+09,5.250000e+09,3.514000e+09,1.764000e+09,1.561000e+09,4.651000e+09,3.095000e+09
GainLossOnInvestments,Gain (Loss) on Investments,1,False,False,Additional,0.500000,NaN,1.230000e+08,NaN,NaN,...,NaN,NaN,NaN,-2.900000e+07,-2.500000e+07,-9.900000e+07,-1.600000e+07,9.000000e+06,9.000000e+07,NaN
GainLossOnSalesOfAssetsAndAssetImpairmentCharges,Gain (Loss) on Sale of Assets and Asset Impair...,1,False,False,Additional,0.500000,NaN,NaN,7.000000e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GainsLossesOnExtinguishmentOfDebt,Gain (Loss) on Extinguishment of Debt,1,False,False,Additional,0.500000,-5.500000e+07,-2.000000e+07,-5.300000e+07,0.000000e+00,...,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,-1.000000e+08,0.000000e+00,0.000000e+00,0.000000e+00,-2.600000e+07
Goodwill,Goodwill,1,False,False,Additional,0.500000,9.780100e+10,NaN,9.780100e+10,9.780100e+10,...,4.361900e+10,4.361400e+10,4.361400e+10,NaN,4.360800e+10,4.360300e+10,4.345000e+10,NaN,4.345700e+10,4.345700e+10
IncomeLossFromContinuingOperationsIncludingPortionAttributableToNoncontrollingInterest,"Income (Loss) from Continuing Operations, Net ...",1,False,True,Additional,0.500000,NaN,8.518000e+09,4.140000e+09,4.965000e+09,...,NaN,NaN,NaN,6.748000e+09,NaN,NaN,NaN,1.989000e+09,1.876000e+09,1.493000e+09
IncomeLossFromDiscontinuedOperationsNetOfTax,"Income (Loss) from Discontinued Operations, Ne...",1,False,True,Additional,0.500000,NaN,0.000000e+00,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00
IncomeLossFromDiscontinuedOperationsNetOfTaxAttributableToReportingEntity,"Income (Loss) from Discontinued Operations, Ne...",1,False,True,Additional,0.500000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IncomeTaxExpenseBenefit,Income Tax Expense (Benefit),1,False,False,Additional,0.500000,8.460000e+08,-1.649000e+09,1.145000e+09,1.200000e+08,...,2.710000e+08,2.350000e+08,6.600000e+07,2.610000e+08,2.630000e+08,2.000000e+08,2.150000e+08,1.800000e+08,-1.500000e+08,-7.000000e+06
NetIncomeLoss,Net Income (Loss) Attributable to Parent,1,False,True,Additional,0.500000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NetIncomeLossAvailableToCommonStockholdersBasic,Net Income (Loss) Available to Common Stockhol...,1,False,True,Additional,0.500000,NaN,NaN,NaN,NaN,...,3.303000e+09,3.481000e+09,3.774000e+09,3.311000e+09,2.999000e+09,2.515000e+09,2.398000e+09,1.914000e+09,1.802000e+09,1.417000e+09
OperatingExpenses,Operating Expenses,1,False,False,Additional,0.500000,4.594000e+09,4.741000e+09,4.816000e+09,4.368000e+09,...,2.308000e+09,2.107000e+09,1.901000e+09,1.940000e+09,1.944000e+09,2.045000e+09,1.941000e+09,2.057000e+09,2.071000e+09,2.082000e+09
OtherNonoperatingIncomeExpense,Other Nonoperating Income (Expense),1,False,False,Additional,0.500000,4.330000e+08,1.220000e+08,2.050000e+08,2.500000e+07,...,1.240000e+08,1.130000e+08,1.430000e+08,4.000000e+07,6.000000e+06,-8.600000e+07,-1.400000e+07,2.200000e+07,1.500000e+07,-2.300000e+07
PaymentsOfDividends,Payments of Dividends,1,False,False,Additional,0.500000,3.086000e+09,2.797000e+09,2.786000e+09,2.785000e+09,...,1.901000e+09,1.914000e+09,1.926000e+09,1.782000e+09,1.736000e+09,1.750000e+09,1.764000e+09,1.561000e+09,1.556000e+09,1.552000e+09
PaymentsToAcquireInvestments,Payments to Acquire Investments,1,False,False,Additional,0.500000,1.140000e+08,3.360000e+08,9.900000e+07,5.700000e+07,...,9.100000e+07,1.970000e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+08,NaN,NaN,NaN
ProceedsFromIssuanceOfLongTermDebt,Proceeds from Issuance of Long-term Debt,1,False,False,Additional,0.500000,4.474000e+09,4.971000e+09,6.960000e+09,7.490000e+08,...,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,1.935000e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
RestructuringCostsAndAssetImpairmentCharges,Restructuring Costs and Asset Impairment Charges,1,False,False,Additional,0.500000,1.160000e+08,6.320000e+08,NaN,NaN,...,NaN,NaN,NaN,-2.200000e+07,NaN,NaN,NaN,3.000000e+06,8.000000e+06,1.200000e+07
UnrealizedGainLossOnInvestments,Unrealized Gain (Loss) on Investments,1,False,False,Additional,0.500000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.500000e+07