In [20]:
import edgar
import pandas as pd
edgar.set_identity("sachiomaximilliano166@gmail.com")
nvda = edgar.Company("SPGI")
tenk = nvda.get_filings(form="8-K")
available_filings = []
for f in tenk:
    if '2.02' in f.items:
        text = f.obj().text()
        available_filings.append(text)

In [31]:

lower_text = available_filings[-1].lower()
idx = lower_text.find('guidance')
start = max(0, idx - 200)
end = min(len(lower_text), idx + 500)
snippet = lower_text[start:end]
print(snippet)

crease in eps from continuing
  operations for third quarter of 2004
  increases guidance to double-digit eps growth in 2004
  new york, oct. 21 /prnewswire-firstcall/ -- the mcgraw-hill companies
  (nyse: mhp) today reported third quarter 2004 diluted earnings per share from
  continuing operations of $1.69, an 11.9% increase over $1.51 for the same
  period last year.

In [6]:
print(tenk.income_statement)

                                        NVIDIA CORP   NVDA
                                        CONSOLIDATED STATEMENT OF INCOME
                                        Jan 28, 2024 to Jan 25, 2026

                                                                  Jan 25, 2026   Jan 26, 2025   Jan 28, 2024
   ──────────────────────────────────────────────────────────────────────────────────────────────────────────
        Revenue:                                                      $215,938       $130,497        $60,922
        Data Center                                                   $193,737       $115,186        $47,525
          Compute                                                     $162,361       $102,196        $38,950
          Networking                                                   $31,376        $12,990         $8,575
        Gaming                                                         $16,042        $11,350        $10,447
        Professional Visualization                                      $3,191         $1,878         $1,553
        Automotive                                                      $2,349         $1,694         $1,091
        OEM and Other                                                     $619           $389           $306
        Cost of revenue:                                               $62,475        $32,639        $16,621
        Inventory purchase obligations in excess of projections         $3,200         $2,000
      Gross profit                                                    $153,463        $97,858        $44,301
    Operating expenses
          Research and development                                     $18,497        $12,914         $8,675
          Sales, general and administrative                             $4,579         $3,491         $2,654
          Total operating expenses                                     $23,076        $16,405        $11,329
      Operating income:                                               $130,387        $81,453        $32,972
        Interest income:                                                $2,300         $1,786           $866
        Interest expense:                                               $(259)         $(247)         $(257)
        Other income, net:                                              $9,022         $1,034           $237
      Total other income, net                                          $11,063         $2,573           $846
      Income before income tax:                                       $141,450        $84,026        $33,818
      Income tax expense                                               $21,383        $11,146         $4,058
      Net income:                                                     $120,067        $72,880        $29,760
    Net income per share:
        Basic (in USD per share)                                          4.93           2.97           1.21
        Diluted (in USD per share)                                        4.90           2.94           1.19
    Weighted average shares used in per share computation:
        Basic (in shares)                                               24,359         24,555         24,690
        Diluted (in shares)                                             24,514         24,804         24,940

   Source: SEC XBRL  •  (In millions, except shares and per share data)

In [8]:
print(tenk.risk_factors)

Item 1A. Risk Factors

The following risk factors should be considered in addition to the other information in this Annual Report on Form 10-K. The following risks could harm our business, financial condition, results of operations or reputation, which could cause our stock price to decline. Additional risks, trends and uncertainties not presently known to us or that we currently believe are immaterial may also harm our business, financial condition, results of operations or reputation.

Risk Factors Summary

Risks Related to Our Industry and Markets

•Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.

•Competition could adversely impact our market share and financial results.

Risks Related to Demand, Supply, and Manufacturing

•Long manufacturing lead times and uncertain supply and capacity availability, combined with a failure to estimate customer demand accurately has led and could lead to mismatches between supply and demand.

•Dependency on third-party suppliers and their technology to manufacture, assemble, test, or package our products reduces our control over product quantity and quality, manufacturing yields, and product delivery schedules and could harm our business.

•Defects in our products have caused and could cause us to incur significant expenses to remediate and could damage our business.

Risks Related to Our Global Operating Business

•Adverse economic conditions may harm our business.

•International sales and operations are a significant part of our business, which exposes us to risks that could harm our business.

•Product, system security and data protection incidents or breaches, as well as cyber-attacks could disrupt our operations and adversely affect our financial condition, stock price and reputation.

•Business disruptions could harm our operations and financial results.

•Climate change may have a long-term impact on our business.

•We may not be able to realize the potential benefits of business investments or acquisitions, nor successfully integrate acquisition targets.

•A significant amount of our revenue stems from a limited number of partners and distributors and we have a concentration of sales to customers who purchase directly or indirectly from us, and our revenue could be adversely affected if we lose or are prevented from selling to any of these customers.

•Commercial arrangements expose us to counterparty risks, which may negatively impact our business, financial condition, or results of operations.

•We may be unable to attract, retain, and motivate our executives and key employees.

•Modification or interruption of our business processes and information systems may disrupt our business and internal controls.

•Our operating results have in the past fluctuated and may in the future fluctuate, and if our operating results are below the expectations of securities analysts or investors, our stock price could decline.

Risks Related to Regulatory, Legal, Our Stock, and Other Matters

•We are subject to complex laws, rules, regulations, and political and other actions, including restrictions on the export of our products, which may adversely impact our business.

•Scrutiny regarding our corporate sustainability practices could result in financial, reputational, or operational harm and liability.

•Issues relating to the responsible use of our technologies, including AI, may result in reputational or financial harm and liability.

•Adequately protecting our IP rights could be costly, and our ability to compete could be harmed if we are unsuccessful or if we are prohibited from making or selling our products.

•We are subject to stringent and changing data privacy and security laws, rules, regulations, and other obligations. These areas could damage our reputation, deter customers, affect product design, or result in legal or regulatory proceedings and liability.

•Our operating results may be adversely impacted by additional tax liabilities, higher than expected tax rates, changes in tax laws, and other tax-related factors.

•Our business is exposed to the burden and risks associated with litigation, investigations, and regulatory proceedings.

•Delaware law, provisions in our governing documents and our agreement with Microsoft could delay or prevent a change in control.

Risk Factors

Risks Related to Our Industry and Markets

Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.

Our accelerated computing platforms experience rapid changes in technology, customer requirements, competitive products, and industry standards.

Our success depends on our ability to:

•timely identify industry changes, adapt our strategies, and develop new or enhance and maintain existing products and technologies that meet the evolving needs of our markets, including addressing unexpected shifts in industry standards or disruptive technological innovations that could render our products incompatible with those developed by other companies;

•develop or secure access to new products and technologies through investments in research and development;

•launch new offerings with new business models including software, services, and cloud solutions, as well as software-, infrastructure-, or platform-as-a-service solutions;

•expand the ecosystem for our products and technologies;

•meet evolving and prevailing customer and industry safety, security, reliability expectations, and compliance standards;

•manage product and software lifecycles to maintain customer and end-user satisfaction;

•develop, acquire, maintain, and secure access to the internal and external infrastructure needed to scale our business, including sufficient energy for powering data centers using our products, acquisition integrations, customer support, e-commerce, IP licensing capabilities, and cloud service capacity; and

•complete technical, financial, operational, compliance, sales and marketing investments for the above activities.

We have invested in research and development in markets where we have a limited operating history, which may not produce meaningful revenue for several years, if at all. If we fail to develop or monetize new products and technologies, or if they do not become widely adopted, our financial results could be adversely affected. Obtaining design wins may involve a lengthy process and depends on our ability to anticipate and provide features and functionality that customers will demand. They also do not guarantee revenue. Failure to obtain a design win may prevent us from obtaining future design wins in subsequent generations. We cannot ensure that our products and technologies will provide value to our customers and partners. If we fail any of these key success criteria, our financial results may be harmed.

We have entered into an intellectual property license arrangement with Groq, Inc., or Groq, that required significant, nonrefundable payments. Successfully incorporating the licensed technology into our architectures and product roadmaps requires significant engineering effort and may not occur on expected timelines or at all. The licensed technology may not achieve the desired results as designed or achieve customer or ecosystem adoption. The economic outcomes of this arrangement depend on our ability to translate the licensed technology into commercially viable products and services over time, and we may be unable to recover the associated costs or realize an adequate return on this spend. If our efforts to use the licensed technology are delayed or unsuccessful, our business, operating results, and financial condition could be negatively impacted.

We entered into multi-year cloud service agreements to support our research and development activities. The timing and availability of these cloud services have changed and may continue to shift, impacting our revenue, expenses, and development timelines, and these arrangements may not deliver anticipated benefits. We also offer or plan to offer standalone software solutions, including NVIDIA AI Enterprise, NVIDIA Omniverse, NVIDIA DRIVE, and other software products. These business models or strategies may not be successful, and we may fail to sell any meaningful standalone software or services. We may incur significant costs and may not achieve any significant revenue from these offerings.

Competition could adversely impact our market share and financial results.

Our target markets remain competitive, and competition may intensify with expanding and changing product and service offerings, industry standards, customer and market needs, new entrants and consolidations. Our competitors’ products, services and technologies, including those mentioned above in this Annual Report on Form 10-K, may be cheaper or provide better functionality or features than ours, which has resulted and may in the future result in lower-than-expected selling prices or demand for our products. Some of our competitors operate their own fabrication facilities, and have longer operating histories, larger customer bases, more comprehensive IP portfolios and patent protections, more design wins, and greater financial, sales, marketing and distribution resources than we do. These competitors may be able to acquire market share and/or prevent us from doing so, more effectively identify and capitalize upon opportunities in new markets and end-user trends, more quickly transition their products, and impinge on our ability to procure sufficient

14


foundry capacity and scarce input materials during a supply-constrained environment, which could harm our business. Some of our customers have in-house expertise and internal development capabilities similar to some of ours and can use or develop their own solutions to replace those we are providing. For example, others may offer cloud-based services that compete with our AI cloud service offerings, and we may not be able to establish market share sufficient to achieve the scale necessary to meet our business objectives. If we are unable to successfully compete in this environment, demand for our products, services and technologies could decrease, which may negatively impact our business.

Risks Related to Demand, Supply, and Manufacturing

Long manufacturing lead times and uncertain supply and capacity availability, combined with a failure to estimate customer demand accurately, has led and could lead to mismatches between supply and demand.

We have long manufacturing lead times and build finished products and maintain inventory in advance of anticipated demand. In periods of shortages impacting the semiconductor industry and/or limited supply or capacity in our supply chain, the lead times for certain supply may be extended. We have previously experienced and may continue to experience extended lead times of more than 12 months. To secure future supply and capacity, we have paid premiums, provided deposits, and entered into long-term supply agreements and capacity commitments, which have increased our product costs and this may continue. We may still be unable to secure sufficient commitments for capacity to address our business needs.

If we inaccurately estimate demand, or our customers change orders, as we have experienced in the past, we may not be able to reduce our supply commitments in time, at the same rate, or at all. Significant mismatches between supply and demand have varied across our market platforms, resulted in both product shortages and excess inventory, significantly harmed our financial results and could reoccur. If we underestimate demand, and our foundry partners and contract manufacturers are unable to increase production or provide sufficient supply, we may not be able to meet increased customer demand in a timely manner, or at all. Our reputation and customer relationships could be damaged and we could lose revenue and market share. Additionally, since some of our products are part of a complex data center buildout, supply constraints or availability issues with respect to any one component have had and may have a broader revenue impact. For example, our ability to sell certain products has been and could be impeded if components necessary for the finished products are not available from third parties.

If we overestimate demand, or if customers cancel or defer orders or choose to purchase from our competitors, we may not be able to utilize on-hand inventory or reduce purchase commitments accordingly. We have had to reduce average selling prices, including due to our channel pricing programs, increase prices for certain of our products as a result of our suppliers’ increase in prices, write down our inventory, incur cancellation penalties, and record impairments, and may have to do so in the future. The impact of these risks would be amplified by our non-cancellable and non-returnable purchase orders placed in advance of our historical lead times and could be exacerbated if we need to make changes to the design of future products. These risks have increased and may continue to increase as our purchase obligations and prepaids have grown and are expected to continue to grow and become a greater portion of our total supply. All of these factors may negatively impact our gross margins and financial results.

Factors that have caused and/or could in the future cause us to underestimate or overestimate demand, and impact the timing and volume of our revenue, include:

•changes in product development cycles and time to market;

•competing technologies and competitor product releases, announcements or other actions;

•changes in business and economic conditions;

•sudden or sustained government lockdowns or public health issues;

•rapidly changing technology or customer requirements;

•the availability of sufficient data center capacity or energy for customers to procure;

•new product introductions and transitions resulting in less demand for existing products;

•new or unexpected end-use cases;

•increase in demand for competitive products;

•changes in end-user demand;

•purchasing decisions made, and inventory levels held by, distributors, ODMs, OEMs, system integrators, other channel partners and other third parties;

15


•the ability of developers, end customers and other third parties to build, enhance, and maintain accelerated computing applications that leverage our platforms;

•the demand for accelerated computing, AI-related cloud services, or large language models;

•changes that impact the ecosystem for the architectures underlying our products and technologies;

•government actions or changes in governmental policies, such as export controls, increased restrictions on gaming usage, or tariffs;

•our customers’ and partners’ ability to secure capital and energy and to build complex datacenter infrastructure timely; and

•the availability of third-party content on our platforms, such as GeForce NOW.

The availability of data centers, energy, and capital to support the buildout of NVIDIA AI infrastructure by our customers and partners is crucial, and any shortage of these and other necessary resources could impact our future revenue and financial performance. Expanding energy capacity to meet demand is a complex, multi-year process involving significant regulatory, technical, and construction challenges. In addition, access to capital can be particularly constrained for less-capitalized companies, which may face difficulties securing financing for large-scale infrastructure projects. These limitations could delay customer and partner deployments or reduce the scale of accelerated computing and AI adoption.

Challenges in estimating demand could become more pronounced or volatile in the future on both a global and regional basis. Extended lead times may occur if we experience other supply constraints caused by natural disasters, pandemics or other events. Geopolitical tensions in regions where we rely on suppliers, contract manufacturers, and assembly partners that are critical to our supply continuity, could have a material adverse impact on us. Publicly announced intentions by governments or other companies to purchase our products can further complicate our demand estimates, as such announcements are often non-binding and may not result in committed volumes.

We continue to increase our supply and capacity purchases with existing and new suppliers to support our demand projections and increasing complexity of our data center products. We expect supply constraints to be a headwind to Gaming in the first quarter of fiscal year 2027 and beyond. We have also entered and may continue to enter into prepaid manufacturing and capacity agreements to supply both current and future products. The increased purchase volumes and integration of new suppliers and contract manufacturers into our supply chain creates more complexity in managing multiple suppliers with variations in production planning, execution and logistics. Our expanding product portfolio and varying component compatibility and quality may lead to increased inventory levels. We have incurred and may in the future incur inventory provisions or impairments if our inventory or supply or capacity commitments exceed demand for our products or demand declines.

We are increasing our U.S.-based manufacturing and investing in specialized equipment and processes to support domestic production. We may experience delays or difficulties in scaling production as planned. Our ability to increase manufacturing capabilities will depend on the domestic manufacturing ecosystem's capacity to ramp production supply to the required volume timely. Delays or shortfalls could impact our ability to meet demand.

Product transitions are complex and we often ship both new and prior architecture products simultaneously as our channel partners prepare to ship and support new products. We are generally in various stages of transitioning the architectures of our Data Center, Gaming, Professional Visualization, and Automotive products. The computing industry is experiencing a broader and faster launch cadence of accelerated computing platforms to meet a growing and diverse set of AI opportunities. We have introduced a new product and architecture cadence of our Data Center solutions where we seek to complete new computing solutions each year and provide a greater variety of Data Center offerings. The increased frequency of these transitions and the larger number of products and product configurations may magnify the challenges associated with managing our supply and demand which may further create volatility in our revenue. Qualification time for new products, customers anticipating product transitions, and channel partners reducing channel inventory of prior architectures ahead of new product introductions can reduce, or create volatility in, our revenue. Customers may delay adopting new architectures if their data center infrastructure is not ready, which could affect the timing of our revenue. We have experienced and may in the future experience reduced demand for current generation architectures when customers anticipate transitions, and we may be unable to sell multiple product architectures at the same time for current and future architecture transitions. Our financial results have been and may in the future be negatively impacted if we are unable to execute our architectural transitions as planned for any reason. The increased frequency and complexity of newly introduced products could result in unanticipated quality or production issues that could increase the magnitude of inventory provisions, warranty, or other costs or result in product delays. For example, our gross margins in the second quarter of fiscal year 2025 were negatively impacted by inventory provisions for low-yielding Blackwell material.


In [13]:
facts = edgar.Company("GOOG").get_facts()

# Common metrics
print(facts.get_revenue())
print(facts.get_net_income())
print(facts.get_total_assets())
# Any XBRL concept
print(facts.get_concept("AccountsPayableCurrent"))

# Time series
revenue_ts = facts.time_series("Revenues")
print(revenue_ts)    # every quarter going back years

350018000000.0
132170000000.0
595281000000.0
None
   period_start  period_end  duration_days  numeric_value fiscal_period  \
0    2025-01-01  2025-03-31             89   9.023400e+10            Q1
1    2026-01-01  2026-03-31             89   1.098960e+11            Q1
2    2023-01-01  2023-12-31            364   3.073940e+11            FY
3    2024-01-01  2024-12-31            365   3.500180e+11            FY
4    2025-01-01  2025-12-31            364   4.028360e+11            FY
5    2024-01-01  2024-09-30            273   2.535490e+11            Q3
6    2024-07-01  2024-09-30             91   8.826800e+10            Q3
7    2025-01-01  2025-09-30            272   2.890070e+11            Q3
8    2025-07-01  2025-09-30             91   1.023460e+11            Q3
9    2024-01-01  2024-06-30            181   1.652810e+11            Q2
10   2024-04-01  2024-06-30             90   8.474200e+10            Q2
11   2025-01-01  2025-06-30            180   1.866620e+11            Q2
12   2025-04-01  2025-06-30             90   9.642800e+10            Q2
13   2019-01-01  2019-12-31            364   1.618570e+11            FY
14   2020-01-01  2020-12-31            365   1.825270e+11            FY
15   2021-01-01  2021-12-31            364   2.576370e+11            FY
16   2020-01-01  2020-06-30            181   7.945600e+10            Q2
17   2020-04-01  2020-06-30             90   3.829700e+10            Q2
18   2021-01-01  2021-06-30            180   1.171940e+11            Q2
19   2021-04-01  2021-06-30             90   6.188000e+10            Q2

    fiscal_year
0          2026
1          2026
2          2025
3          2025
4          2025
5          2025
6          2025
7          2025
8          2025
9          2025
10         2025
11         2025
12         2025
13         2021
14         2021
15         2021
16         2021
17         2021
18         2021
19         2021

C:\Users\Sachio\AppData\Local\Temp\ipykernel_40192\3854283658.py:8: UserWarning: Unknown concept 'AccountsPayableCurrent'.
  Use list_supported_concepts() to see available concept names,
  or search_concepts() to search this company's raw XBRL tags.
  print(facts.get_concept("AccountsPayableCurrent"))

In [3]:
msft = edgar.Company("MSFT")
facts = msft.get_facts()
cf = facts.income_statement(as_dataframe=True, periods=1000, annual=False)
cf

,label,depth,is_abstract,is_total,section,confidence,Q3 2026,Q2 2026,Q1 2026,Q4 2025,...,Q1 2012,Q4 2011,Q3 2011,Q2 2011,Q1 2011,Q4 2010,Q3 2010,Q2 2010,Q1 2010,Q2 2009
concept,,,,,,,,,,,,,,,,,,,,,
RevenueFromContractWithCustomerExcludingAssessedTax,Total Revenue,0,False,True,NaN,0.950000,8.288600e+10,8.127300e+10,7.767300e+10,7.644100e+10,...,1.737200e+10,NaN,1.642800e+10,1.995300e+10,1.619500e+10,NaN,1.450300e+10,1.902200e+10,1.292000e+10,1.662900e+10
CostOfGoodsAndServicesSold,Cost of Revenue,0,False,False,NaN,0.353474,2.682800e+10,2.597800e+10,2.404300e+10,2.401400e+10,...,3.777000e+09,3.708000e+09,3.897000e+09,4.833000e+09,3.139000e+09,3.170000e+09,2.755000e+09,3.628000e+09,2.842000e+09,3.907000e+09
GrossProfit,Gross Profit,0,False,True,NaN,0.522400,5.605800e+10,5.529500e+10,5.363000e+10,5.242700e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OperatingExpensesAbstract,Operating expenses:,0,True,False,NaN,0.314199,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ResearchAndDevelopmentExpense,Research and Development Expense,1,False,False,NaN,0.626900,8.915000e+09,8.504000e+09,8.146000e+09,8.829000e+09,...,2.329000e+09,2.393000e+09,2.269000e+09,2.185000e+09,2.196000e+09,2.350000e+09,2.220000e+09,2.079000e+09,2.065000e+09,2.290000e+09
SellingAndMarketingExpense,Selling and Marketing Expense,1,False,False,NaN,0.567200,6.814000e+09,6.584000e+09,5.717000e+09,7.285000e+09,...,2.900000e+09,3.916000e+09,3.393000e+09,3.825000e+09,2.806000e+09,3.602000e+09,3.203000e+09,3.619000e+09,2.790000e+09,3.662000e+09
GeneralAndAdministrativeExpense,General and Administrative Expense,1,False,False,NaN,0.656700,1.931000e+09,1.932000e+09,1.806000e+09,1.990000e+09,...,1.163000e+09,1.179000e+09,1.160000e+09,9.450000e+08,9.380000e+08,9.870000e+08,1.152000e+09,1.124000e+09,7.410000e+08,8.310000e+08
OperatingExpenses,Operating Expenses,1,False,True,NaN,0.671600,1.766000e+10,1.702000e+10,1.566900e+10,3.974900e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OperatingIncomeLoss,Operating Income (Loss),0,False,True,NaN,0.570997,3.839800e+10,3.827500e+10,3.796100e+10,3.432300e+10,...,7.203000e+09,6.171000e+09,5.709000e+09,8.165000e+09,7.116000e+09,5.930000e+09,5.173000e+09,8.513000e+09,4.482000e+09,5.939000e+09
OtherNonoperatingIncomeExpense,Other Nonoperating Income (Expense),0,False,False,NaN,0.425982,-4.910000e+08,9.541000e+09,-4.923000e+09,-1.864000e+09,...,-4.000000e+06,0.000000e+00,7.000000e+06,0.000000e+00,-3.800000e+07,NaN,NaN,NaN,NaN,NaN
IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest,Income (Loss) from Continuing Operations befor...,0,False,True,NaN,0.682779,3.934000e+10,4.824600e+10,3.430100e+10,3.261600e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IncomeTaxExpenseBenefit,Income Tax Expense (Benefit),0,False,True,NaN,0.800604,7.562000e+09,9.788000e+09,6.554000e+09,5.383000e+09,...,1.568000e+09,4.450000e+08,7.930000e+08,1.863000e+09,1.820000e+09,1.506000e+09,1.335000e+09,2.221000e+09,1.191000e+09,1.464000e+09
NetIncomeLoss,Net Income (Loss) Attributable to Parent,0,False,True,NaN,0.776435,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,...,5.738000e+09,NaN,5.232000e+09,6.634000e+09,5.410000e+09,NaN,4.006000e+09,6.662000e+09,3.574000e+09,4.174000e+09
EarningsPerShareBasic,"Earnings Per Share, Basic",0,False,False,NaN,0.845921,4.280000e+00,5.180000e+00,3.730000e+00,3.663797e+00,...,6.800000e-01,NaN,6.200000e-01,7.800000e-01,6.300000e-01,NaN,4.600000e-01,7.500000e-01,4.000000e-01,4.700000e-01
EarningsPerShareDiluted,"Earnings Per Share, Diluted",0,False,False,NaN,0.836858,4.270000e+00,5.160000e+00,3.720000e+00,3.648091e+00,...,6.800000e-01,NaN,6.100000e-01,7.700000e-01,6.200000e-01,NaN,4.500000e-01,7.400000e-01,4.000000e-01,4.700000e-01
NonoperatingIncomeExpenseAbstract,Other income (expense):,0,True,False,NaN,0.268700,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NonoperatingIncomeExpense,Nonoperating Income (Expense),1,False,True,NaN,0.417900,9.420000e+08,9.971000e+09,-3.660000e+09,-1.707000e+09,...,1.030000e+08,1.480000e+08,3.160000e+08,3.320000e+08,1.140000e+08,9.400000e+07,1.680000e+08,3.700000e+08,2.830000e+08,-3.010000e+08
WeightedAverageNumberOfSharesOutstandingBasic,"Weighted Average Number of Shares Outstanding,...",0,False,False,NaN,0.691843,7.426000e+09,7.431000e+09,7.433000e+09,NaN,...,8.392000e+09,NaN,8.420000e+09,8.497000e+09,8.614000e+09,NaN,8.767000e+09,8.856000e+09,8.914000e+09,8.903000e+09
WeightedAverageNumberOfDilutedSharesOutstanding,"Weighted Average Number of Shares Outstanding,...",0,False,True,NaN,0.691843,7.445000e+09,7.460000e+09,7.466000e+09,NaN,...,8.490000e+09,NaN,8.510000e+09,8.570000e+09,8.695000e+09,NaN,8.876000e+09,8.951000e+09,8.983000e+09,8.914000e+09
InterestExpenseNonoperating,Interest Expense (non-operating),0,False,False,NaN,0.314199,7.780000e+08,7.360000e+08,6.980000e+08,6.150000e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AdditionalItems,Additional Financial Items,0,True,False,Additional,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AmortizationOfIntangibleAssets,Amortization of Intangible Assets,1,False,False,Additional,0.500000,1.100000e+09,1.200000e+09,1.500000e+09,1.500000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CapitalizedComputerSoftwareAmortization1,"Capitalized Computer Software, Amortization",1,False,False,Additional,0.500000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CommonStockDividendsPerShareDeclared,"Common Stock, Dividends, Per Share, Declared",1,False,False,Additional,0.500000,9.100000e-01,9.100000e-01,9.100000e-01,NaN,...,2.000000e-01,NaN,1.600000e-01,1.600000e-01,1.600000e-01,NaN,1.300000e-01,1.300000e-01,1.300000e-01,1.300000e-01
CostOfGoodsSold,Cost of Goods Sold (Deprecated 2018-01-31),1,False,False,Additional,0.500000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CostsAndExpenses,Costs and Expenses,1,False,False,Additional,0.500000,NaN,NaN,NaN,NaN,...,1.016900e+10,1.119600e+10,1.071900e+10,1.178800e+10,9.079000e+09,1.010900e+10,9.330000e+09,1.050900e+10,8.438000e+09,1.069000e+10
EquitySecuritiesFvNiRealizedGainLoss,"Equity Securities, FV-NI, Realized Gain (Loss)",1,False,False,Additional,0.500000,3.200000e+07,3.000000e+06,7.100000e+07,1.700000e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ForeignCurrencyTransactionGainLossBeforeTax,"Foreign Currency Transaction Gain (Loss), befo...",1,False,False,Additional,0.500000,-2.950000e+08,-5.000000e+07,-2.200000e+07,5.900000e+07,...,-4.000000e+07,-1.200000e+07,5.500000e+07,-2.700000e+07,-4.200000e+07,NaN,NaN,NaN,NaN,NaN
GainLossOnDerivativeInstrumentsNetPretax,"Gain (Loss) on Derivative Instruments, Net, Pr...",1,False,True,Additional,0.500000,1.240000e+08,3.700000e+07,1.579000e+09,7.000000e+06,...,2.700000e+07,-1.150000e+08,-6.500000e+07,1.080000e+08,-5.000000e+06,NaN,NaN,NaN,NaN,NaN
GainLossOnInvestments,Gain (Loss) on Investments,1,False,False,Additional,0.500000,1.652000e+09,3.390000e+08,-5.720000e+08,-6.300000e+07,...,3.000000e+06,1.000000e+08,1.870000e+08,1.180000e+08,3.400000e+07,NaN,NaN,NaN,NaN,NaN
GoodwillImpairmentLoss,"Goodwill, Impairment Loss",1,False,False,Additional,0.500000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InterestExpense,Interest Expense,1,False,False,Additional,0.500000,NaN,NaN,NaN,NaN,...,9.400000e+07,9.400000e+07,8.400000e+07,7.200000e+07,4.500000e+07,NaN,NaN,NaN,NaN,NaN
InvestmentIncomeNet,"Investment Income, Net",1,False,True,Additional,0.500000,7.300000e+08,8.400000e+08,9.760000e+08,7.690000e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalesRevenueGoodsNet,"Sales Revenue, Goods, Net (Deprecated 2018-01-31)",1,False,True,Additional,0.500000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalesRevenueNet,"Revenue, Net (Deprecated 2018-01-31)",1,False,True,Additional,0.500000,NaN,NaN,NaN,NaN,...,1.737200e+10,NaN,1.642800e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
import pandas as pd
nvda = edgar.Company("MSFT")
fil = nvda.get_filings(form="8-K")
for f in fil:
    if f.items and '2.02' in f.items:
        ed_date = f.filing_date
        print(ed_date)

2026-04-29
2026-01-28
2025-10-29
2025-07-30
2025-04-30
2025-01-29
2024-10-30
2024-07-30
2024-04-25
2024-01-30
2023-10-24
2023-07-25
2023-04-25
2023-01-24
2022-10-25
2022-07-26
2022-04-26
2022-01-25
2021-10-26
2021-07-27
2021-04-27
2021-01-26
2020-10-27
2020-07-22
2020-04-29
2020-01-29
2019-10-23
2019-07-18
2019-04-24
2019-01-30
2018-10-24
2018-07-19
2018-04-26
2018-01-31
2017-10-26
2017-07-20
2017-04-27
2017-01-26
2016-10-20
2016-07-19
2016-04-21
2016-01-28
2015-10-22
2015-07-21
2015-04-23
2015-01-26
2014-10-23
2014-07-22
2014-04-24
2014-01-23
2013-10-24
2013-07-18
2013-04-18
2013-01-24
2012-10-18
2012-07-19
2012-04-19
2012-01-19
2011-10-20
2011-07-21
2011-04-28
2011-01-27
2010-10-28
2010-07-22
2010-04-22
2010-01-28
2009-10-23
2009-07-23
2009-04-23
2009-01-22
2008-10-23
2008-07-17
2008-04-24
2008-01-24
2007-10-25
2007-07-19
2007-04-26
2007-01-25
2006-10-26
2006-07-20
2006-04-27
2006-01-26
2005-10-27
2005-07-21
2005-04-28
2005-04-11
2005-01-27
2004-11-08
2004-10-21

In [9]:

# Example: Apple
import edgar
edgar.set_identity("sachiomaximilliano166@gmail.com")
company = edgar.Company("MSFT")
facts = company.get_facts()
income_df = facts.income_statement(as_dataframe=True, periods=1000, annual=False)
print(income_df.loc['EarningsPerShareBasic'])
print(income_df.loc['EarningsPerShareDiluted'])
row = income_df[income_df['label'] == 'Earnings Per Share, Basic']
row

label          Earnings Per Share, Basic
depth                                  0
is_abstract                        False
is_total                           False
section                              NaN
                         ...
Q4 2010                              NaN
Q3 2010                             0.46
Q2 2010                             0.75
Q1 2010                              0.4
Q2 2009                             0.47
Name: EarningsPerShareBasic, Length: 74, dtype: object
label          Earnings Per Share, Diluted
depth                                    0
is_abstract                          False
is_total                             False
section                                NaN
                          ...
Q4 2010                                NaN
Q3 2010                               0.45
Q2 2010                               0.74
Q1 2010                                0.4
Q2 2009                               0.47
Name: EarningsPerShareDiluted, Length: 74, dtype: object

,label,depth,is_abstract,is_total,section,confidence,Q3 2026,Q2 2026,Q1 2026,Q4 2025,...,Q1 2012,Q4 2011,Q3 2011,Q2 2011,Q1 2011,Q4 2010,Q3 2010,Q2 2010,Q1 2010,Q2 2009
concept,,,,,,,,,,,,,,,,,,,,,
EarningsPerShareBasic,"Earnings Per Share, Basic",0,False,False,NaN,0.845921,4.28,5.18,3.73,3.663797,...,0.68,NaN,0.62,0.78,0.63,NaN,0.46,0.75,0.4,0.47